### ISSUE TITLE
 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by 3400442579** [renzhezhilu/gifsicle-wasm-browser#2]
![image](https://user-images.githubusercontent.com/34226979/188353385-ed435662-8522-4436-8a71-3f94068e937e.png)
![image](https://user-images.githubusercontent.com/34226979/188353573-937adbf8-5de3-4676-b3a6-0c5445bb7273.png)

**Comment by renzhezhilu** [comment]
我试了两个大的gif都没问题，应该不是文件体积的问题，估计是尺寸，你试试加上把高度调整下再试试
```javascript
--resize _x1280 -O1 --lossy=50 1.gif  -o /out/out.gif
```
谨慎使用`-O3`或`-O2`, 耗时会成倍上涨，并且压缩效果和`-O1`几乎无差别。

![image](https://user-images.githubusercontent.com/7707921/188490809-fc320288-ed93-43ef-ab1e-b8149709386d.png)

![image](https://user-images.githubusercontent.com/7707921/188490707-b872c248-1e4a-4c8c-810f-c987d4da5e13.png)
